#ifndef CATALOG_EXPERIMENTELEMENTTEMPLATEAPI_H
#define CATALOG_EXPERIMENTELEMENTTEMPLATEAPI_H

#ifdef CATALOG_EXPERIMENTELEMENTTEMPLATE_EXPORT
  #define CATALOG_EXPERIMENTELEMENTTEMPLATE_API __declspec(dllexport)
#else
  #define CATALOG_EXPERIMENTELEMENTTEMPLATE_API __declspec(dllimport)
#endif

#endif