#ifndef CATALOG_EXPERIMENTELEMENTTEMPLATEGUIAPI_H
#define CATALOG_EXPERIMENTELEMENTTEMPLATEGUIAPI_H

#ifdef CATALOG_EXPERIMENTELEMENTTEMPLATEGUI_EXPORT
  #define CATALOG_EXPERIMENTELEMENTTEMPLATEGUI_API __declspec(dllexport)
#else
  #define CATALOG_EXPERIMENTELEMENTTEMPLATEGUI_API __declspec(dllimport)
#endif

#endif